[package]
name = "namada-ts-claim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bip39 = {version = "1.0.1", default-features = false}
ed25519-compact = "1.0.11"
hex = "0.4.3"
zeroize = "1.6.0"
inquire = "0.6.2"
